//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCollectionWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannedBook
    {
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Authors { get; set; }
        public string Categories { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> Pages { get; set; }
        public string ISBN { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string ReadingPeriods { get; set; }
        public string Comments { get; set; }
        public string Summary { get; set; }
        public string CoverPath { get; set; }
        public Nullable<bool> IsAudioBook { get; set; }
        public Nullable<bool> OKToDonate { get; set; }
    }
}
